In [4]:
import torch
xx=[[1,2,3],[4,5,6]]
x = torch.tensor(xx)
y = torch.tensor([[7,8,9],[10,11,12]])
z = x + y
print(z) 
print(z.size()) 
print(x.size()) 
# print(xx.size())

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])
torch.Size([2, 3])


### the content of xx and x is the same, but z being a tensor allows us to use tensor methods

In [2]:
print(x.type())

torch.LongTensor


In [5]:
d = torch.tensor(xx, dtype = torch.float)

In [6]:
print(d.type())

torch.FloatTensor


In [7]:
print(d)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
d=d.type(torch.int)

In [10]:
print(d)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [11]:
import numpy as np

d= np.array([[1,2,3],[4,5,6]])

In [12]:
print(d)

[[1 2 3]
 [4 5 6]]


In [13]:
d=torch.from_numpy(d)

In [14]:
print(d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
### print type and shape here
### change type to something else from https://pytorch.org/docs/stable/tensors.html

In [16]:
print(z.shape) #shape same as size()
print(x.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [17]:
x= x.unsqueeze(0)

In [18]:
print(x.shape)

torch.Size([1, 2, 3])


In [19]:
x= x.unsqueeze(2)

In [20]:
print(x.shape)

torch.Size([1, 2, 1, 3])


In [21]:
x= x.squeeze()

In [22]:
print(x.shape)

torch.Size([2, 3])


In [23]:
z= z.squeeze()

### what happened?

In [24]:
print(z.shape)

torch.Size([2, 3])
