In [1]:
import torch
import torchvision
from torchvision import transforms
from torchvision.datasets import CIFAR10
from torchvision import transforms

In [2]:
train_transforms = transforms.Compose([
  transforms.ToTensor(),
  transforms.Normalize(
      (0.4914, 0.4822, 0.4465),
      (0.2023, 0.1994, 0.2010))])
train_dataset = CIFAR10(root="./train/",
                    train=True, 
                    download=True,
                       transform = train_transforms)
length=len(train_dataset)

100%|██████████| 170498071/170498071 [00:11<00:00, 14603467.65it/s]


Extracting ./train/cifar-10-python.tar.gz to ./train/


In [3]:
from torch.utils.data import Dataset, random_split

train_data, _ = random_split(train_dataset, [int(length/10), length - int(length/10)], torch.Generator().manual_seed(42))

In [4]:
len(train_data.indices)

5000

In [5]:
train_data.dataset.data[0].shape

(32, 32, 3)

In [6]:
train_data.dataset.data[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [7]:
len(train_data)

5000

In [8]:
import pandas as pd
df_t = pd.DataFrame(train_data.dataset.data[train_data.indices].reshape(5000,3072))

In [9]:
df_t.columns

RangeIndex(start=0, stop=3072, step=1)

In [10]:
from sklearn.preprocessing import StandardScaler

# create a scaler object
std_scaler = StandardScaler()
std_scaler
# fit and transform the data
df_std = pd.DataFrame(std_scaler.fit_transform(df_t), columns=df_t.columns)

In [11]:
df_std.insert(0, 'label',[train_data.dataset.targets[i] for i in train_data.indices])

In [12]:
df_std 

label         0         1         2         3         4         5  \
0         6 -0.941713 -1.076758 -0.944543 -0.815551 -1.021071 -0.899195   
1         2  0.716505  0.902495  0.403488  0.510508  0.684741  0.263607   
2         8  0.458258  0.448917  0.490861  0.496695  0.488992  0.529030   
3         6 -1.512575 -1.654040 -1.506223 -1.520019 -1.650263 -1.505875   
4         6 -1.349471 -1.076758 -1.356442 -1.257570 -1.049035 -1.215174   
...     ...       ...       ...       ...       ...       ...       ...   
4995      9 -0.017460  0.421427  0.765460 -0.553102 -0.084273  0.339442   
4996      6 -0.724242 -0.788117 -0.882134 -0.235400 -0.307986 -0.431546   
4997      2  0.091275 -0.183345 -0.445272  0.137554 -0.140201 -0.393629   
4998      3  1.056304  0.586365  0.316116  1.063032  0.614830  0.339442   
4999      0  1.586390  1.507267  1.426994  1.587930  1.509682  1.426410   

             6         7         8  ...      3062      3063      3064  \
0    -0.741065 -0.932752 -0.842170  ... -0.945781 -0.483259 -1.219043   
1     0.231925  0.390780  0.072602  ... -0.370347 -0.342798  0.296203   
2     0.509922  0.503421  0.542694  ... -0.370347 -1.045106 -0.958356   
3    -1.547257 -1.693078 -1.528249  ... -0.619183 -0.795396 -0.876891   
4    -0.518668 -0.270986 -0.829465  ... -0.930229  0.578005  0.556890   
...        ...       ...       ...  ...       ...       ...       ...   
4995  0.106826  0.686462  1.101721  ... -1.536768 -1.763020 -1.805590   
4996 -0.115572 -0.172425 -0.321258  ...  0.111774 -0.046268  0.002929   
4997  0.204125 -0.087944 -0.359373  ... -0.961334  0.375117  0.540597   
4998  1.093716  0.672382  0.377527  ... -0.074853  0.390723  0.084394   
4999  1.608011  1.531269  1.444761  ... -0.650288  0.421937  0.116980   

          3065      3066      3067      3068      3069      3070      3071  
0    -1.068914 -0.660450 -1.352511 -1.216152 -0.542450 -1.222633 -1.128947  
1    -0.338593 -0.318699  0.332094 -0.335261 -0.373637  0.261707 -0.458209  
2    -0.556135 -1.033270 -0.996152 -0.597983 -1.094927 -1.078987 -0.671625  
3    -0.882449 -0.784724 -0.850369 -0.922522 -0.665222 -0.727853 -0.824066  
4    -0.618290  0.551214  0.542669 -0.412532  0.439732  0.469195 -0.488697  
...        ...       ...       ...       ...       ...       ...       ...  
4995 -1.519538 -1.716773 -1.789860 -1.417057 -1.708790 -1.749335 -1.342363  
4996  0.096493  0.349270  0.461679  0.561084  0.086760  0.118061  0.197285  
4997 -0.291976  0.691022  0.931424  0.082003  0.900129  1.123582  0.288750  
4998 -0.152128  0.395873  0.040528 -0.227081  0.393692  0.022297 -0.244792  
4999 -0.602751  0.395873  0.072924 -0.628891  0.378345  0.070179 -0.625893  

[5000 rows x 3073 columns]

### Now create a class that takes df_std and for each pair of an image datapoint and its label from Cifar10 it creates a new datapoint, which consists of two images, the original label and a new class label. 
### The new class  label will be  1 if the second image is of the same class as the original, otherwise 0


In [13]:
from tqdm import tqdm
import numpy as np
class Cifar10_Cont_Dataset(Dataset):
    def __init__(self, data_df: pd.DataFrame, transform=None, is_test=False):
        # method will run once when class object is created.
        super(Cifar10_Cont_Dataset, self).__init__()
        dataset = []
        labels_positive = {}
        labels_negative = {}
        if is_test == False:
            # for each label create a set of same label images.
            for i in list(data_df.label.unique()):
                labels_positive[i] = data_df[data_df.label == i].to_numpy()
            # for each label create a set of image of different label.
            for i in list(data_df.label.unique()):
                labels_negative[i] = data_df[data_df.label != i].to_numpy()

        for i, row in tqdm(data_df.iterrows(), total=len(data_df)):
            data = row.to_numpy()
            # if test then only image will be returned.
            if is_test:
                label = -1
                first = np.asarray(data[1:]).reshape(32, 32, 3)
                second = -1
                dis = -1
            else:
                # label and image of the index for each row in df
                label = data[0]
                first = np.asarray(data[1:]).reshape(32, 32, 3)
                # probability of same label image == 0.5
                if np.random.randint(0, 2) == 0:
                    # randomly select same label image
                    second = labels_positive[label][
                        np.random.randint(0, len(labels_positive[label]))
                    ]
                else:
                    # randomly select different(negative) label 
                    second = labels_negative[label][
                        np.random.randint(0, len(labels_negative[label]))
                    ]
                # cosine is 1 for same and 0 for different label
                dis = 1.0 if second[0] == label else 0.0
                # reshape image
                second = np.asarray(second[1:]).reshape(32, 32, 3)

            # apply transform on both images
            if transform != None:
                first = transform(first.astype(np.float32))
                if second is not -1:
                    second = transform(second.astype(np.float32))

            # append to dataset list. 
            # this random list is created once and used in every epoch
            dataset.append((first, second, dis, label))
        
        self.dataset = dataset
        self.transform = transform
        self.is_test = is_test

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, i):
        return self.dataset[i]


<>:49: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:49: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/tmp/ipykernel_2706926/1212003039.py:49: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if second is not -1:


### instantiate with is-test = False

In [14]:
train_transforms = transforms.Compose([
  transforms.ToTensor(),
  transforms.Normalize(
      (0.4914, 0.4822, 0.4465),
      (0.2023, 0.1994, 0.2010))])
cont_dataset = Cifar10_Cont_Dataset(df_std, transform=train_transforms, is_test = False)
#cont_dataset = Cifar10_Cont_Dataset(df_t, is_test = False)

100%|██████████| 5000/5000 [00:01<00:00, 4506.40it/s]


In [15]:
cont_dataset[0][0].shape

torch.Size([3, 32, 32])

In [16]:
cont_dataset[0][0]

tensor([[[ -7.0841,  -6.4605,  -6.0923,  ...,  -6.1476,  -6.5350,  -7.3463],
         [ -3.5005,  -3.8233,  -5.0501,  ...,  -5.8497,  -6.5094,  -7.1959],
         [ -5.8465,  -6.7987,  -8.1248,  ...,  -4.9673,  -5.0353,  -5.7611],
         ...,
         [-11.8457, -11.7041, -12.1854,  ...,  -3.2720,  -4.0326,  -3.3694],
         [-11.5026, -11.0329, -11.7083,  ...,  -2.9998,  -4.6399,  -5.1698],
         [ -9.1725,  -9.1784,  -9.9514,  ...,  -4.8179,  -5.6938,  -5.1105]],

        [[ -7.8182,  -7.5390,  -7.0960,  ...,  -7.5110,  -7.9014,  -8.5783],
         [ -4.2149,  -4.8380,  -5.8821,  ...,  -6.9301,  -7.6794,  -8.3097],
         [ -6.5374,  -7.6620,  -8.5823,  ...,  -5.8039,  -6.1011,  -6.8335],
         ...,
         [-11.1537, -11.5846, -11.1507,  ...,  -6.3141,  -8.0364,  -8.5971],
         [-11.5988, -11.3726, -11.5786,  ...,  -6.3202,  -7.7961,  -8.8808],
         [-10.1649, -10.5331, -11.1907,  ...,  -8.5318,  -9.2012,  -8.5498]],

        [[ -6.9206,  -6.6950,  -6.4113,  ...

In [17]:
train_transforms = transforms.Compose([
  transforms.ToTensor(),
])
cont_dataset1 = Cifar10_Cont_Dataset(df_std, transform=train_transforms, is_test = False)
#cont_dataset = Cifar10_Cont_Dataset(df_t, is_test = False)

100%|██████████| 5000/5000 [00:00<00:00, 7726.35it/s]


In [18]:
cont_dataset1[0][0]

tensor([[[-0.9417, -0.8156, -0.7411,  ..., -0.7522, -0.8306, -0.9948],
         [-0.2168, -0.2820, -0.5302,  ..., -0.6920, -0.8255, -0.9643],
         [-0.6914, -0.8840, -1.1523,  ..., -0.5135, -0.5272, -0.6741],
         ...,
         [-1.9050, -1.8763, -1.9737,  ..., -0.1705, -0.3244, -0.1902],
         [-1.8356, -1.7406, -1.8772,  ..., -0.1155, -0.4473, -0.5545],
         [-1.3642, -1.3654, -1.5218,  ..., -0.4833, -0.6605, -0.5424]],

        [[-1.0768, -1.0211, -0.9328,  ..., -1.0155, -1.0933, -1.2283],
         [-0.3583, -0.4825, -0.6907,  ..., -0.8997, -1.0491, -1.1747],
         [-0.8214, -1.0456, -1.2291,  ..., -0.6751, -0.7344, -0.8804],
         ...,
         [-1.7418, -1.8278, -1.7412,  ..., -0.7768, -1.1203, -1.2321],
         [-1.8306, -1.7855, -1.8266,  ..., -0.7780, -1.0723, -1.2886],
         [-1.5447, -1.6181, -1.7492,  ..., -1.2190, -1.3525, -1.2226]],

        [[-0.9445, -0.8992, -0.8422,  ..., -1.0461, -1.0718, -1.1846],
         [-0.2349, -0.3142, -0.5617,  ..., -0

In [19]:
train_transforms = transforms.Compose([
  transforms.ToPILImage("RGB"),
  transforms.ToTensor(),
  transforms.Normalize(
      (0.4914, 0.4822, 0.4465),
      (0.2023, 0.1994, 0.2010))])
cont_dataset2 = Cifar10_Cont_Dataset(df_std, transform=train_transforms, is_test = False)

100%|██████████| 5000/5000 [00:01<00:00, 3513.52it/s]


In [20]:
cont_dataset2[0][0]

tensor([[[-1.9444,  1.2735,  0.2267,  ...,  1.2735,  0.5368,  0.6144],
         [ 1.4285,  1.2735,  0.4787,  ...,  1.2735,  0.7113,  0.4593],
         [-2.1577,  1.2735,  1.0602,  ...,  1.2735,  1.2153, -1.0140],
         ...,
         [ 0.3817,  1.2541,  0.9439,  ..., -1.2272,  0.4981, -0.0060],
         [ 0.3430, -1.2272,  0.4787,  ...,  1.2735,  2.0876, -1.6537],
         [ 2.1845,  1.2735,  1.6999,  ...,  1.2735,  1.1184, -0.2580]],

        [[-2.0249, -1.4546,  1.3381,  ...,  1.8298,  1.3381,  0.2171],
         [ 2.1838, -0.5106,  1.3381,  ..., -0.5892,  1.3381,  0.4138],
         [-0.8842, -1.2579,  1.3381,  ...,  1.3774,  1.3381,  0.8858],
         ...,
         [ 0.4138,  0.5514,  1.3381,  ..., -0.6089, -1.1792,  1.7708],
         [-2.3396, -1.9856, -1.1792,  ...,  2.1248,  1.3381,  1.1611],
         [-0.1172, -2.1626,  1.3381,  ..., -0.2352,  1.3381,  0.7874]],

        [[-0.0167,  1.8953,  0.7442,  ...,  0.5100,  0.4320,  1.5051],
         [-0.1728, -0.5630, -0.6020,  ..., -1

In [21]:
train_transforms = transforms.Compose([
  transforms.ToPILImage("RGB"),
  transforms.ToTensor(),
])
cont_dataset3 = Cifar10_Cont_Dataset(df_std, transform=train_transforms, is_test = False)

100%|██████████| 5000/5000 [00:01<00:00, 4953.41it/s]


In [22]:
cont_dataset3[0][0]

tensor([[[0.0980, 0.7490, 0.5373,  ..., 0.7490, 0.6000, 0.6157],
         [0.7804, 0.7490, 0.5882,  ..., 0.7490, 0.6353, 0.5843],
         [0.0549, 0.7490, 0.7059,  ..., 0.7490, 0.7373, 0.2863],
         ...,
         [0.5686, 0.7451, 0.6824,  ..., 0.2431, 0.5922, 0.4902],
         [0.5608, 0.2431, 0.5882,  ..., 0.7490, 0.9137, 0.1569],
         [0.9333, 0.7490, 0.8353,  ..., 0.7490, 0.7176, 0.4392]],

        [[0.0784, 0.1922, 0.7490,  ..., 0.8471, 0.7490, 0.5255],
         [0.9176, 0.3804, 0.7490,  ..., 0.3647, 0.7490, 0.5647],
         [0.3059, 0.2314, 0.7490,  ..., 0.7569, 0.7490, 0.6588],
         ...,
         [0.5647, 0.5922, 0.7490,  ..., 0.3608, 0.2471, 0.8353],
         [0.0157, 0.0863, 0.2471,  ..., 0.9059, 0.7490, 0.7137],
         [0.4588, 0.0510, 0.7490,  ..., 0.4353, 0.7490, 0.6392]],

        [[0.4431, 0.8275, 0.5961,  ..., 0.5490, 0.5333, 0.7490],
         [0.4118, 0.3333, 0.3255,  ..., 0.2353, 1.0000, 0.7490],
         [0.6157, 0.3529, 0.0275,  ..., 0.2745, 0.5765, 0.